#!/bin/bash

# ORGANISATION DETAILS
ORGS="Hospital1 Hospital2 Hospital3"
PEERSCOUNT="2 2 2"
USE_COUCHDB="TRUE FALSE TRUE"
USE_INTERMEDIATE_CAS="TRUE TRUE TRUE"

# ORDERER DETAILS
ORDERER_TYPE="solo"
ORDERERS_COUNT=1
ORDERER_PROFILE_NAME="OrdererProfile"
NUM_KAFKAS=5
NUM_ZOOKEEPERS=4

# NETWORK DETAILS
CHANNEL_NAME="immutableehr"

DOCKER_NETWORK_TYPE="DOCKER-SWARM-SINGLE"
DOCKER_EXTERNAL_NETWORK_NAME="hieext"
DOCKER_SMARM_NAME="hie"

# CHAINCODE DETAILS
CHAINCODE_NAME="hiechain"
CHAINCODE_VERSION="1.0"
CHAINCODE_PATH="github.com/chaincode/hie/"